const PEOPLE = [
    "My mother",
    "My father",
    "My brother",
    "My sister",
    "My aunt",
    "My uncle",
    "My grandmother",
    "My grandfather"
]

const JOBS = [
    "Writer",
    "Nuclear engineer",
    "Software engineer",
    "Physicist",
    "Graphic designer",
    "Computer hardware engineer",
    "Linguist",
    "Architect",
    "Painter",
    "Violinist",
    "Actor",
    "Surgeon",
    "Chemist",
    "Teacher",
    "Taxi driver",
    "Floral designer",
    "Exobiologist",
    "Civil engineer",
    "Astronomer"
]

const ADVANCED_JOBS = [
    "Nuclear engineer",
    "Physicist",
    "Computer hardware engineer",
    "Surgeon",
    "Exobiologist",
]

const FUTURE_TIMES =  [
    "In a few days",
    "Never",
    "In a week",
    "In a few weeks",
    "In several months",
    "In about a year",
    "Immediately"
]

const HIDING_PLACES = [
    "Under the bed",
    "Behind the closet",
    "In a safe",
    "Under the floorboards",
    "The bathroom cabinet",
    "Behind the bathroom mirror",
    "Under the kitchen sink",
    "In the basement",
    "Behind my bookshelf"
]

const NAMES = [
    "Sylvaine Rooijakker",
    "Lilian Way",
    "Gerrit Rigby",
    "Esme Hollands",
    "Nkosana Langlais",
    "Roxanne Peyton",
    "Benjamin Hardy",
    "Danny James",
    "Ju Li",
    "Alexander Patel",
    "Hong Wu",
    "Asher Cropper",
    "Zachary Daives",
    "Andrew Kelly",
    "Ajeet Gadhavi",
    "Tina Powell",
    "Katie Simmons",
    "Jack Marshall",
    "Rosie Clarke",
    "Mei Ueda",
    "Hwan Moon",
    "Ai Chen",
    "Kevin Campbell",
    "Samuel Murray",
    "Vidya Darzi",
    "Rilla Armistead",
    "Mat Ashworth",
    "Jun Bai",
    "Stacy Barton",
    "Khole Brown",
    "Maya Singh",
    "Hideki Tsukuda",
    "Akane Wakahisa",
    "Jin Kim",
    "Carolyn Turner",
    "Vidya Darzi",
    "Hector Salamanca",
    "Julia Reyes",
    "Vernoika Volkov",
    "Kayla Hughes",
    "Qing Sung"
]

const NAME_PRONOUN_MAP = {
    "Sylvaine Rooijakker": "F",
    "Lilian Way": "F",
    "Gerrit Rigby": "M",
    "Esme Hollands": "F",
    "Nkosana Langlais": "F",
    "Roxanne Peyton": "F",
    "Benjamin Hardy": "M",
    "Danny James": "M",
    "Ju Li": "F",
    "Alexander Patel": "M",
    "Hong Wu": "M",
    "Asher Cropper": "M",
    "Zachary Daives": "M",
    "Andrew Kelly": "M",
    "Ajeet Gadhavi": "M",
    "Tina Powell": "F",
    "Katie Simmons": "F",
    "Jack Marshall": "M",
    "Rosie Clarke": "F",
    "Mei Ueda": "F",
    "Hwan Moon": "M",
    "Ai Chen": "M",
    "Kevin Campbell": "M",
    "Samuel Murray": "M",
    "Vidya Darzi": "F",
    "Rilla Armistead": "F",
    "Mat Ashworth": "M",
    "Jun Bai": "F",
    "Stacy Barton": "F",
    "Khole Brown": "F",
    "Maya Singh": "F",
    "Hideki Tsukuda": "F",
    "Akane Wakahisa": "M",
    "Jin Kim": "M",
    "Carolyn Turner": "F",
    "Vidya Darzi": "F",
    "Hector Salamanca": "M",
    "Julia Reyes": "F",
    "Vernoika Volkov": "F",
    "Kayla Hughes": "F",
    "Qing Sung": "M"
}

const COUNTRIES = [
    "Canada",
    "China",
    "Russia",
    "Germany",
    "France",
    "The United Kingdom",
    "The United States",
    "Japan",
    "Mexico",
    "India",
    "Brazil",
    "South Africa",
    "Indonesia",
    "Australia",
    "Israel"
]

const RELIGION_DESCRIPTIONS = {
    "Islam": "an approved religious belief.",
    "Christianity": "an approved religious belief.",
    "Buddhism": "a dangerous Heathen belief.",
    "Hinduism": "an approved religious belief.",
    "Judaism": "an approved religious belief.",
    "Confucianism": "an uncommon but accepted religious belief.",
    "Syntheism": "an uncommon but accepted religious belief.",
    "None": "which is suspicious and unlikely."
}
